-- Builds the required database

DROP TABLE IF EXISTS cards;

CREATE TABLE cards
  (
    id INTEGER PRIMARY KEY, s_id INTEGER,
    name VARCHAR(255), type VARCHAR(255), hp VARCHAR(255),
    atkName1 VARCHAR(255), atkName2 VARCHAR(255),
    atkType1 INTEGER, atkType2 INTEGER,
    rarity VARCHAR(255)
  );

DROP TABLE IF EXISTS names;
CREATE TABLE names
  (id INTEGER PRIMARY KEY, name VARCHAR(255));

DROP TABLE IF EXISTS types;
CREATE TABLE types
  (id INTEGER PRIMARY KEY, type VARCHAR(255));

DROP TABLE IF EXISTS rarities;
CREATE TABLE rarities
  (id INTEGER PRIMARY KEY, rarity VARCHAR(255));
